# Generated by Django 6.0 on 2025-12-19 15:09

import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Метрика')),
                ('unit', models.CharField(help_text='кг, см, %', max_length=20, verbose_name='Ед. изм.')),
                ('is_chartable', models.BooleanField(default=True, verbose_name='Строить график?')),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Метрика тела',
                'verbose_name_plural': 'Метрики тела',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО Атлета')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('coach_notes', models.TextField(blank=True, verbose_name='Приватные заметки тренера')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Клиент активен')),
            ],
            options={
                'verbose_name': 'Профиль Клиента',
                'verbose_name_plural': 'База Клиентов',
            },
        ),
        migrations.CreateModel(
            name='ClientStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Статус')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('color_code', models.CharField(default='#FFFFFF', max_length=7, verbose_name='HEX цвет')),
                ('icon', models.FileField(blank=True, null=True, upload_to='status_icons/')),
            ],
            options={
                'verbose_name': 'CRM-Статус',
                'verbose_name_plural': 'CRM-Статусы',
            },
        ),
        migrations.CreateModel(
            name='HistoricalWorkoutSession',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('workout', '🏋️ Тренировка'), ('cardio', '🏃 Кардио'), ('meal', '🥦 Питание / БЖУ'), ('checkin', '📸 Чекин формы'), ('payment', '💰 Оплата')], default='workout', max_length=20)),
                ('status', models.CharField(choices=[('planned', 'План 📅'), ('done', 'Сделано ✅'), ('reviewed', 'Проверено Коучем 🔥'), ('missed', 'Пропущено ❌')], default='planned', max_length=20)),
                ('title', models.CharField(max_length=255, verbose_name='Тема (День ног)')),
                ('description', models.TextField(help_text='Упражнения, подходы, веса', verbose_name='План тренировки (Задание)')),
                ('scheduled_at', models.DateTimeField(verbose_name='Дата и время тренировки')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда выполнил')),
                ('client_comment', models.TextField(blank=True, verbose_name='Отчет клиента (Ощущения)')),
                ('coach_feedback', models.TextField(blank=True, verbose_name='Ответ тренера')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Тренировка / Событие',
                'verbose_name_plural': 'historical Календарь событий',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MediaReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='workouts/%Y/%m/%d/', verbose_name='Видео/Фото файл')),
                ('media_type', models.CharField(choices=[('video', 'Видео'), ('image', 'Фото')], default='image', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Медиа-отчет',
                'verbose_name_plural': 'Медиа-отчеты',
            },
        ),
        migrations.CreateModel(
            name='MetricLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Значение')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата замера')),
            ],
            options={
                'verbose_name': 'Замер',
                'verbose_name_plural': 'Журнал прогресса',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название программы')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Описание стратегии')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='programs/', verbose_name='Обложка программы (Dark Theme)')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Программа / Цель',
                'verbose_name_plural': 'Программы',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('workout', '🏋️ Тренировка'), ('cardio', '🏃 Кардио'), ('meal', '🥦 Питание / БЖУ'), ('checkin', '📸 Чекин формы'), ('payment', '💰 Оплата')], default='workout', max_length=20)),
                ('status', models.CharField(choices=[('planned', 'План 📅'), ('done', 'Сделано ✅'), ('reviewed', 'Проверено Коучем 🔥'), ('missed', 'Пропущено ❌')], default='planned', max_length=20)),
                ('title', models.CharField(max_length=255, verbose_name='Тема (День ног)')),
                ('description', models.TextField(help_text='Упражнения, подходы, веса', verbose_name='План тренировки (Задание)')),
                ('scheduled_at', models.DateTimeField(verbose_name='Дата и время тренировки')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда выполнил')),
                ('client_comment', models.TextField(blank=True, verbose_name='Отчет клиента (Ощущения)')),
                ('coach_feedback', models.TextField(blank=True, verbose_name='Ответ тренера')),
            ],
            options={
                'verbose_name': 'Тренировка / Событие',
                'verbose_name_plural': 'Календарь событий',
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
