# Generated by Django 6.0 on 2025-12-19 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='Тренер'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт входа'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='statuses',
            field=models.ManyToManyField(blank=True, to='clients.clientstatus', verbose_name='CRM Теги'),
        ),
        migrations.AddField(
            model_name='historicalworkoutsession',
            name='client',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clients.clientprofile', verbose_name='Атлет'),
        ),
        migrations.AddField(
            model_name='historicalworkoutsession',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalworkoutsession',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='metriclog',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics_log', to='clients.clientprofile'),
        ),
        migrations.AddField(
            model_name='metriclog',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.bodymetric'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athletes', to='clients.program', verbose_name='Текущая программа'),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='clients.clientprofile', verbose_name='Атлет'),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mediareport',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='clients.workoutsession', verbose_name='Тренировка'),
        ),
    ]
