# Generated by Django 6.0 on 2025-12-23 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Название атрибута')),
                ('attr_type', models.CharField(choices=[('text', 'Текст'), ('number', 'Число'), ('date', 'Дата'), ('boolean', 'Да/Нет')], default='text', max_length=10)),
                ('icon', models.FileField(blank=True, null=True, upload_to='attributes/icons/', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Справочник атрибутов',
                'verbose_name_plural': 'Справочник атрибутов',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.FileField(blank=True, null=True, upload_to='categories/icons/', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Категория / Программа',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Название тега')),
                ('color', models.CharField(default='#808080', max_length=7, verbose_name='Цвет (HEX)')),
                ('icon', models.FileField(blank=True, null=True, upload_to='tags/icons/', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.RemoveField(
            model_name='metriclog',
            name='metric',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='program',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='statuses',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='client',
        ),
        migrations.RemoveField(
            model_name='historicalworkoutsession',
            name='client',
        ),
        migrations.RemoveField(
            model_name='metriclog',
            name='client',
        ),
        migrations.RemoveField(
            model_name='historicalworkoutsession',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalworkoutsession',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='mediareport',
            name='workout',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='created_by',
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента (Display Name)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='clients/avatars/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('categories', models.ManyToManyField(blank=True, related_name='clients', to='clients.category', verbose_name='Программы')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='Тренер')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт для входа')),
                ('tags', models.ManyToManyField(blank=True, related_name='clients', to='clients.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.attribute')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='clients.client')),
            ],
            options={
                'verbose_name': 'Параметр клиента',
                'verbose_name_plural': 'Параметры клиента',
                'unique_together': {('client', 'attribute')},
            },
        ),
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Задание / План')),
                ('client_feedback', models.TextField(blank=True, verbose_name='Отчет клиента')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='sessions/attachments/', verbose_name='Вложение')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('status', models.CharField(choices=[('planned', 'Запланировано'), ('completed', 'Выполнено'), ('cancelled', 'Отменено'), ('missed', 'Пропущено')], default='planned', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='clients.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Сессия / Тренировка',
                'verbose_name_plural': 'Сессии',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SessionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Сообщение')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='comments/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='clients.worksession')),
            ],
            options={
                'verbose_name': 'Комментарий к сессии',
                'verbose_name_plural': 'Комментарии к сессиям',
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='BodyMetric',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.DeleteModel(
            name='ClientStatus',
        ),
        migrations.DeleteModel(
            name='ClientProfile',
        ),
        migrations.DeleteModel(
            name='MetricLog',
        ),
        migrations.DeleteModel(
            name='HistoricalWorkoutSession',
        ),
        migrations.DeleteModel(
            name='MediaReport',
        ),
        migrations.DeleteModel(
            name='WorkoutSession',
        ),
    ]
