# Generated by Django 6.0 on 2025-12-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_attribute_category_tag_remove_metriclog_metric_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksession',
            name='status',
            field=models.CharField(choices=[('planned', 'Запланировано'), ('completed', 'Выполнено'), ('review', 'Проверено'), ('cancelled', 'Отменено'), ('missed', 'Пропущено')], default='planned', max_length=20, verbose_name='Статус'),
        ),
    ]
