# Generated by Django 6.0 on 2025-12-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_worksession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужской (Male)'), ('F', 'Женский (Female)'), ('O', 'Другой (Other)')], default='M', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='worksession',
            name='status',
            field=models.CharField(choices=[('planned', 'Запланировано'), ('completed', 'Выполнено'), ('review', 'Проверено'), ('missed', 'Пропущено'), ('cancelled', 'Отменено')], default='planned', max_length=20, verbose_name='Статус'),
        ),
    ]
