# Generated by Django 6.0 on 2025-12-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_id', models.IntegerField(choices=[(1, 'Слот 1'), (2, 'Слот 2'), (3, 'Слот 3'), (4, 'Слот 4'), (5, 'Слот 5')], unique=True, verbose_name='Номер слота (1-5)')),
                ('is_active', models.BooleanField(default=False, verbose_name='Включен в ротацию?')),
                ('media', models.FileField(blank=True, null=True, upload_to='website/carousel/', verbose_name='Медиа файл')),
                ('media_type', models.CharField(choices=[('image', 'Картинка'), ('video', 'Видео')], default='image', editable=False, max_length=10)),
                ('headline', models.CharField(blank=True, max_length=100, verbose_name='Заголовок (H1)')),
                ('subheadline', models.CharField(blank=True, max_length=200, verbose_name='Подзаголовок')),
                ('button_count', models.IntegerField(choices=[(0, 'Без кнопок'), (1, 'Одна кнопка'), (2, 'Две кнопки')], default=1, verbose_name='Кол-во кнопок')),
                ('btn1_text', models.CharField(blank=True, max_length=50, verbose_name='Кнопка 1: Текст')),
                ('btn1_link', models.CharField(blank=True, max_length=200, verbose_name='Кнопка 1: Ссылка')),
                ('btn1_style', models.CharField(choices=[('white', 'Белая'), ('outline', 'Контур')], default='white', max_length=20, verbose_name='Кнопка 1: Стиль')),
                ('btn2_text', models.CharField(blank=True, max_length=50, verbose_name='Кнопка 2: Текст')),
                ('btn2_link', models.CharField(blank=True, max_length=200, verbose_name='Кнопка 2: Ссылка')),
                ('btn2_style', models.CharField(choices=[('white', 'Белая'), ('outline', 'Контур')], default='outline', max_length=20, verbose_name='Кнопка 2: Стиль')),
            ],
            options={
                'verbose_name': 'Слайд карусели',
                'verbose_name_plural': 'Настройки Карусели',
                'ordering': ['slot_id'],
            },
        ),
    ]
