# Generated by Django 6.0 on 2025-12-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('system', 'Системное'), ('workout', 'Тренировка'), ('message', 'Сообщение'), ('action', 'Требует действия')], default='system', max_length=20),
        ),
    ]
